
        name: MERN CI/CD

        on:
          push:
            branches: [main]

        jobs:
          build-and-deploy:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout repo
                uses: actions/checkout@v3

              - name: Setup Node
                uses: actions/setup-node@v3
                with:
                  node-version: '18'

              - name: Install & Test Frontend
                run: |
                  cd frontend
                  npm install
                  npm run build

              - name: Install & Test Backend
                run: |
                  cd backend
                  npm install
                  echo "PORT=5000
MONGO_URI=mongodb://localhost/test" > .env
                  node server.js & sleep 5
                  curl http://localhost:5000/health
